if: NOT (commit_message =~ /^\[docs\]/) OR (type = push AND branch = master) OR (type = pull_request AND NOT branch = master)

language: node_js
node_js: "stable"

addons:
  chrome:  stable
  firefox: latest
  apt:
    packages:
      - dbus

before_install:
  - export $(dbus-launch)

notifications:
  email: false
