if: NOT (commit_message =~ /^\[docs\]/) OR (branch = master) OR (type != push)

language: node_js
node_js: "stable"
services:
  - xvfb

addons:
  chrome:  stable
  firefox: latest
  apt:
    packages:
      - dbus

before_install:
  - export $(dbus-launch)

notifications:
  email: false
