name: Authentication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Kerberos auth example
        run: npm run kerberos-auth

      - name: Auth with certificates
        run: npm run certificate-auth
